#!/usr/bin/env python3
"""
cronometer_sync.py — Pulls nutrition data from Cronometer and pushes to the app.

Cronometer's export requires a short-lived nonce token generated by the GWT app.
This script uses Playwright to log in, navigate to the export section, click the
export button to capture the nonce, then downloads the CSV with our date range.

Setup (one-time):
    pip3 install playwright
    python3 -m playwright install chromium

Usage:
    python3 cronometer_sync.py [--days 7] [--headed]
"""

import os
import sys
import csv
import io
import logging
import argparse
import urllib.parse
from datetime import date, timedelta
from typing import Optional

from dotenv import load_dotenv
import requests

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)s  %(message)s")
log = logging.getLogger(__name__)

API_BASE        = os.environ["NEXT_PUBLIC_APP_URL"].rstrip("/")
SYNC_SECRET     = os.environ["SYNC_SECRET"]
CRONOMETER_USER = os.environ.get("CRONOMETER_USER", "")
CRONOMETER_PASS = os.environ.get("CRONOMETER_PASS", "")
BOT_TOKEN       = os.environ.get("TELEGRAM_BOT_TOKEN", "")
CHAT_ID         = os.environ.get("TELEGRAM_CHAT_ID", "")

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
from config import MAX_RETRIES, RETRY_DELAY, CRONOMETER_SYNC_DAYS


# ── Telegram alert ────────────────────────────────────────────────────────────

def send_alert(message: str) -> None:
    if not BOT_TOKEN or not CHAT_ID:
        return
    try:
        requests.post(
            f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
            json={"chat_id": CHAT_ID, "text": message, "parse_mode": "Markdown"},
            timeout=10,
        )
    except Exception:
        pass


# ── Retry helper ──────────────────────────────────────────────────────────────

def with_retry(fn, *args, label: str = "", **kwargs):
    last_exc = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            last_exc = e
            log.warning(f"{label} attempt {attempt}/{MAX_RETRIES} failed: {e}")
            if attempt < MAX_RETRIES:
                import time
                time.sleep(RETRY_DELAY * attempt)
    raise last_exc


def date_range(days: int) -> list:
    today = date.today()
    return [today - timedelta(days=i) for i in range(days - 1, -1, -1)]


def fetch_cronometer_csv(start: date, end: date, headed: bool = False) -> list:
    try:
        from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
    except ImportError:
        log.error("Run: pip3 install playwright && python3 -m playwright install chromium")
        sys.exit(1)

    csv_text: Optional[str] = None

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=not headed)
        context = browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/123.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 900},
        )
        page = context.new_page()

        # ── 1. Login ──────────────────────────────────────────────────────────
        log.info("Logging in…")
        page.goto("https://cronometer.com/login/", wait_until="load", timeout=30000)

        try:
            page.wait_for_selector("input[type='password']", timeout=15000)
        except PWTimeout:
            log.error("Login form didn't appear.")
            browser.close()
            return []

        for sel in ["input[type='email']", "input[name='username']", "input[placeholder*='mail' i]"]:
            try:
                page.fill(sel, CRONOMETER_USER, timeout=3000)
                break
            except Exception:
                continue

        page.fill("input[type='password']", CRONOMETER_PASS)

        for sel in ["button[type='submit']", "input[type='submit']", "button:has-text('Log')", "button:has-text('Sign')"]:
            try:
                page.click(sel, timeout=3000)
                break
            except Exception:
                continue

        try:
            page.wait_for_url(lambda url: "login" not in url.lower(), timeout=20000)
        except PWTimeout:
            log.error("Login failed — still on login page. Check credentials in scripts/.env")
            browser.close()
            return []

        log.info(f"Logged in → {page.url}")

        # ── 2. Wait for GWT app to fully initialise ───────────────────────────
        log.info("Waiting for app to initialise…")
        page.wait_for_timeout(5000)

        # ── 3. Navigate to account/export section and click Export Data ──────
        log.info("Navigating to export section…")
        page.evaluate("window.location.hash = '#account'")
        page.wait_for_timeout(3000)

        page.screenshot(path=os.path.join(SCRIPT_DIR, "debug_account.png"))
        log.info("Screenshot saved: scripts/debug_account.png")

        export_clicked = False
        for sel in [
            "button.btn-borderless-jungle-green:has-text('Export Data')",
            "button:has-text('Export Data')",
            ".btn-borderless-jungle-green",
        ]:
            try:
                loc = page.locator(sel)
                if loc.count() > 0:
                    log.info(f"Clicking Export Data: {sel}")
                    loc.first.click()
                    page.wait_for_timeout(3000)
                    export_clicked = True
                    break
            except Exception:
                continue

        if not export_clicked:
            log.error("Could not find 'Export Data' button. Run with --headed to debug.")
            browser.close()
            return []

        # ── 4. Click 'EXPORT DAILY NUTRITION' and capture the download ────────
        log.info("Clicking 'EXPORT DAILY NUTRITION' and waiting for download…")
        daily_btn = None
        for sel in [
            "text=EXPORT DAILY NUTRITION",
            "button:has-text('EXPORT DAILY NUTRITION')",
            "text=Export Daily Nutrition",
            "button:has-text('Export Daily Nutrition')",
        ]:
            try:
                loc = page.locator(sel)
                if loc.count() > 0:
                    daily_btn = loc.first
                    log.info(f"Found button: {sel}")
                    break
            except Exception:
                continue

        if daily_btn is None:
            log.error("Could not find 'EXPORT DAILY NUTRITION' button. Run with --headed to debug.")
            browser.close()
            return []

        with page.expect_download(timeout=30000) as dl_info:
            daily_btn.click()

        download = dl_info.value
        log.info(f"Download started: {download.suggested_filename}")

        # ── 5. Re-download with our desired date range via Playwright's session ─
        # The clicked download uses Cronometer's default date range; we capture
        # the nonce from its URL and re-fetch with our range using the same session.
        nonce = None
        download_url = download.url
        log.info(f"Download URL: {download_url}")
        if "nonce=" in download_url:
            parsed = urllib.parse.urlparse(download_url)
            params = urllib.parse.parse_qs(parsed.query)
            nonce = params.get("nonce", [None])[0]
            log.info(f"Captured nonce: {nonce}")

        if nonce:
            export_url = (
                f"https://cronometer.com/export"
                f"?nonce={nonce}"
                f"&generate=dailySummary"
                f"&start={start}"
                f"&end={end}"
            )
            log.info(f"Fetching with custom date range: {export_url}")
            resp = context.request.get(export_url)
            if resp.ok:
                csv_text = resp.text()
                log.info(f"Downloaded {len(csv_text)} chars of CSV")
            else:
                log.warning(f"Custom date range fetch failed (HTTP {resp.status}), using downloaded file instead")
                nonce = None

        if not nonce:
            # Fall back to reading the file Cronometer already downloaded
            csv_path = download.path()
            with open(csv_path, encoding="utf-8-sig") as f:
                csv_text = f.read()
            log.info(f"Read {len(csv_text)} chars from downloaded file")

        browser.close()

    if not csv_text or csv_text.strip().startswith("<!"):
        log.error("Export returned no valid CSV data.")
        return []

    log.info(f"CSV preview (first 500 chars):\n{csv_text[:500]}")

    # ── 6. Parse CSV ──────────────────────────────────────────────────────────
    rows = []
    reader = csv.DictReader(io.StringIO(csv_text))

    def safe_float(v: str) -> Optional[float]:
        try:
            return float(v) if v and v.strip() else None
        except (ValueError, TypeError):
            return None

    for row in reader:
        day_str = row.get("Date", "").strip()
        if not day_str:
            continue
        rows.append({
            "date":         day_str,
            "calories":     safe_float(row.get("Energy (kcal)")),
            "protein_g":    safe_float(row.get("Protein (g)")),
            "carbs_g":      safe_float(row.get("Carbs (g)")),
            "fat_g":        safe_float(row.get("Fat (g)")),
            "iron_mg":      safe_float(row.get("Iron (mg)")),
            "sodium_mg":    safe_float(row.get("Sodium (mg)")),
            "potassium_mg": safe_float(row.get("Potassium (mg)")),
            "magnesium_mg": safe_float(row.get("Magnesium (mg)")),
            "vitamin_d_iu": safe_float(row.get("Vitamin D (IU)")),
            "calcium_mg":   safe_float(row.get("Calcium (mg)")),
        })

    log.info(f"Parsed {len(rows)} days from Cronometer")
    return rows


def push_to_api(nutrition: list) -> None:
    url     = f"{API_BASE}/api/cronometer/sync"
    headers = {"Authorization": f"Bearer {SYNC_SECRET}", "Content-Type": "application/json"}
    log.info(f"Pushing {len(nutrition)} rows to {url}")
    resp = requests.post(url, headers=headers, json={"nutrition": nutrition}, timeout=30)
    resp.raise_for_status()
    log.info(f"Done: {resp.json()}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--days",   type=int, default=CRONOMETER_SYNC_DAYS)
    parser.add_argument("--headed", action="store_true", help="Show browser window")
    args = parser.parse_args()

    try:
        days      = date_range(args.days)
        nutrition = with_retry(
            fetch_cronometer_csv, days[0], days[-1], args.headed,
            label="Cronometer scrape",
        )
        if not nutrition:
            raise RuntimeError("No nutrition rows parsed from CSV")
        with_retry(push_to_api, nutrition, label="API push")
        log.info("Cronometer sync complete ✓")

    except Exception as e:
        log.error(f"Cronometer sync failed after {MAX_RETRIES} attempts: {e}")
        send_alert(
            f"⚠️ *Cronometer sync failed*\n\n"
            f"All {MAX_RETRIES} retries exhausted.\n"
            f"`{e}`\n\n"
            f"Check `/tmp/cronometer_sync.log`"
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
