#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# install_cron.sh — Installs the Personal Tracker crontab.
#
# Edit the SCHEDULE block below to change times, then re-run:
#   bash scripts/install_cron.sh
#
# All times are PST/PDT (TZ=America/Los_Angeles is set at the top of the crontab).
# Format: "MINUTE HOUR" — e.g. "30 19" = 7:30 PM
# ─────────────────────────────────────────────────────────────────────────────

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
PYTHON="${PYTHON:-$(which python3)}"

# ── Schedule ──────────────────────────────────────────────────────────────────
MORNING_GARMIN="0 9"      # 9:00 AM  — backfill previous night's sleep
EVENING_GARMIN="30 19"    # 7:30 PM  — today's activity + metrics
CRONOMETER="35 19"        # 7:35 PM  — nutrition sync
TELEGRAM="45 19"          # 7:45 PM  — survey + food reminder + adjust-plan agent
# ─────────────────────────────────────────────────────────────────────────────

crontab - <<EOF
TZ=America/Los_Angeles

# ── Personal Tracker — Mac Mini ──────────────────────────────────────────────
# Generated by install_cron.sh — edit that file to change times.

# Morning Garmin — backfills previous night's sleep (~8h Garmin delay)
${MORNING_GARMIN} * * * cd "${SCRIPTS_DIR}" && ${PYTHON} garmin_sync.py >> /tmp/garmin_sync_morning.log 2>&1

# Evening Garmin — today's activity, HRV, metrics
${EVENING_GARMIN} * * * cd "${SCRIPTS_DIR}" && ${PYTHON} garmin_sync.py >> /tmp/garmin_sync_evening.log 2>&1

# Cronometer nutrition sync
${CRONOMETER} * * * cd "${SCRIPTS_DIR}" && ${PYTHON} cronometer_sync.py >> /tmp/cronometer_sync.log 2>&1

# Evening orchestrator — food reminder + survey + adjust-plan agent
${TELEGRAM} * * * cd "${SCRIPTS_DIR}" && ${PYTHON} telegram_checkin_cron.py >> /tmp/telegram_cron.log 2>&1
EOF

echo "✓ Crontab installed:"
crontab -l
